feat: generate unique 10-characters id for sample
mylims/mylims pull request #202
Opened 2021-11-11 15:18 UTC by maasencioh

Fixes #201

2021-11-13 12:07 UTC, targos requested changes
Please add a unique index on this field to the samples collection in a migration.

2021-11-15 06:58 UTC, targos commented on app/Controllers/Http/MeasurementController.ts
> +      characters: 'CDEHKMPRTUWXY0123456789',
The charset seems a bit small

2021-11-15 06:59 UTC, targos commented on app/Controllers/Http/MeasurementController.ts
>        });
Can you override `Sample.create` so that it adds the uuid automatically?
It should also have some retry logic in case of collision.

2021-11-15 09:02 UTC, maasencioh commented on app/Controllers/Http/MeasurementController.ts
> +      characters: 'CDEHKMPRTUWXY0123456789',
I took the `distinguishable` charset and added the numbers as you mentioned, otherwise we could simply take the uppercases + numbers

2021-11-15 12:42 UTC, targos commented on app/Controllers/Http/MeasurementController.ts
> +      characters: 'CDEHKMPRTUWXY0123456789',
@lpatiny

2021-11-15 12:46 UTC, targos commented on app/Models/Sample.ts
> +    throw new Error('Uuid10 was colliding 10 times');
tbh, I think we can just make a `while(true)` the loop should always eventually return

2021-11-15 12:46 UTC, targos commented on app/Models/Sample.ts
> +      const sample = await Sample.findBy('uuid10', uuid10);
this is an anti-pattern. Try to create it, and if it fails because of the unique constraint, try again

2021-11-15 12:46 UTC, targos commented on app/Models/Sample.ts
> +  public async create(data: Partial<ModelAttributes<Sample>>) {
Please also accept (and pass) the options object: https://github.com/zakodium/adonis-mongodb/blob/638a5ec3054c92aec75fc144eb7ca331ee567b50/adonis-typings/odm.ts#L108
It's important if we want to create in a transaction.

2021-11-15 12:46 UTC, targos commented on app/Models/Sample.ts
> +    if (data.uuid10) return Sample.create(data);
do we really need to support an external uuid10?

2021-11-16 09:17 UTC, maasencioh commented on app/Models/Sample.ts
> +    throw new Error('Uuid10 was colliding 10 times');
I'm not sure, if every code is taken then it will infinitely loop

2021-11-16 09:48 UTC, targos commented on app/Models/Sample.ts
> +    throw new Error('Uuid10 was colliding 10 times');
if you think it's possible that every code is taken, then the charset is definitely too small.

2021-11-17 09:46 UTC, maasencioh commented on app/Models/Sample.ts
> +    if (data.uuid10) return Sample.create(data);
@lpatiny do you need this?

2021-11-22 15:29 UTC, targos requested changes

2021-11-22 15:29 UTC, targos commented on app/Models/Sample.ts
> +        sample = await Sample.create({ ...data, uuid10 }, options);
Shouldn't this be `super.create` ?

2021-11-22 15:29 UTC, targos commented on app/Models/Sample.ts
> +        sample = undefined;
This line doesn't seem useful.
On the other hand, you need to check the kind of error and rethrow if it isn't a duplicate on the uuid10 field.

2021-11-29 10:42 UTC, maasencioh commented on app/Models/Sample.ts
> +        sample = await Sample.create({ ...data, uuid10 }, options);
super gives me `MongodbDocument<IdType>`, while Sample is a `MongodbModel<IdType>`, that is what I was expecting

2021-11-29 10:59 UTC, targos commented on app/Models/Sample.ts
> +        sample = await Sample.create({ ...data, uuid10 }, options);
but `Sample.create` seems really wrong as it is this method. doesn't it lead to infinite recursion?

2021-12-02 16:07 UTC, closed without merging